import type { Logo } from "@components/footer/types";
import DBU from "/src/images/logos/foerderinnen/logo-dbu.png";
import Mercator from "/src/images/logos/foerderinnen/Stiftung_Mercator_Blau_RGB.png";
import BMUV from "/src/images/logos/foerderinnen/BMUV.png";
import Weizenbaum from "/src/images/logos/traegerinnen/weizenbaum.png";

export const supporters: Logo[] = [
  {
    name: "Deutscher Naturschutzring",
    logo: "/images/logos/traegerinnen/dnr.svg",
    url: "https://www.dnr.de/",
    alt: "Deutscher Naturschutzring Logo",
    width: 296,
    height: 100,
  },
  {
    name: "Institut für ökologische Wirtschaftsforschung",
    logo: "/images/logos/traegerinnen/ioew.svg",
    url: "https://www.ioew.de/",
    alt: "Institut für ökologische Wirtschaftsforschung Logo",
    width: 289,
    height: 100,
  },
  {
    name: "Technische Universität Berlin",
    logo: "/images/logos/traegerinnen/tu-berlin.svg",
    url: "https://www.tu-berlin.de/",
    alt: "Technische Universität Berlin Logo",
    width: 233,
    height: 130,
  },
  {
    name: "Germanwatch e.V.",
    logo: "/images/logos/traegerinnen/germanwatch.svg",
    url: "https://germanwatch.org/",
    alt: "Germanwatch e.V. Logo",
    width: 296,
    height: 108,
  },
  {
    name: "BUND",
    logo: "/images/logos/traegerinnen/bund.svg",
    url: "https://www.bund.net/",
    alt: "BUND Logo",
    width: 296,
    height: 100,
  },
  {
    name: "Brot für die Welt",
    logo: "/images/logos/traegerinnen/brot-fuer-die-welt.svg",
    url: "https://www.brot-fuer-die-welt.de/",
    alt: "Brot für die Welt Logo",
    width: 231,
    height: 100,
  },
  {
    name: "Chaos Computer Club",
    logo: "/images/logos/traegerinnen/ccc.svg",
    url: "https://www.ccc.de/",
    alt: "Chaos Computer Club Logo",
    width: 179,
    height: 130,
  },
  {
    name: "Forum InformatikerInnen für Frieden und gesellschaftliche Verantwortung",
    logo: "/images/logos/traegerinnen/fiff-schwarz.svg",
    url: "https://www.fiff.de/",
    alt: "Forum InformatikerInnen für Frieden und gesellschaftliche Verantwortung Logo",
    width: 262,
    height: 100,
  },
  {
    name: "konzeptwerk neue ökonomie",
    logo: "/images/logos/traegerinnen/konzeptwerk.svg",
    url: "https://www.konzeptwerk-neue-oekonomie.org/",
    alt: "konzeptwerk neue ökonomie Logo",
    width: 246,
    height: 130,
  },
  {
    name: "Open Knowledge Foundation",
    logo: "/images/logos/traegerinnen/okfn.svg",
    url: "https://okfn.de/",
    alt: "Open Knowledge Foundation Logo",
    width: 287,
    height: 130,
  },
  {
    name: "Einstein Center Digital Future",
    logo: "/images/logos/traegerinnen/einstein_center.svg",
    url: "https://www.digital-future.berlin/",
    alt: "Einstein Center Digital Future Logo",
    width: 130,
    height: 130,
  },
  {
    name: "Free Software Foundation Europe",
    logo: "/images/logos/traegerinnen/fsfe-cropped.svg",
    url: "https://fsfe.org/",
    alt: "Free Software Foundation Europe Logo",
    width: 249,
    height: 130,
  },
  {
    name: "Weizenbaum-Institut",
    logo: Weizenbaum,
    url: "https://weizenbaum-institut.de/",
    alt: "Weizenbaum-Institut Logo",
    width: 296,
    height: 105,
  },
];

export const media: Logo[] = [
  {
    name: "Reset",
    logo: "/images/logos/foerderinnen/logo-reset.svg",
    url: "https://reset.org/",
    alt: "Reset Logo",
    width: 296,
    height: 100,
  },
  {
    name: "Heise Online",
    logo: "/images/logos/foerderinnen/logo-heise-online.svg",
    url: "https://www.heise.de/",
    alt: "Heise Logo",
    width: 296,
    height: 100,
  },
];

export const specialThanks: Logo[] = [
  {
    name: "Cleaner Web",
    logo: "/images/logos/thanks_to/logo-cleaner-web.svg",
    url: "https://cleaner-web.com/",
    alt: "Cleaner Web Logo",
    width: 296,
    height: 100,
  },
  {
    name: "Uber Space",
    logo: "/images/logos/thanks_to/logo-uberspace.svg",
    url: "https://uberspace.de/",
    alt: "Uber Space Logo",
    width: 170,
    height: 100,
  },
  {
    name: "Web Shaped",
    logo: "/images/logos/thanks_to/web_shaped_logo_23_inline_trans_dark_regular-big.svg",
    url: "https://webshaped.de/",
    alt: "Web Shaped (Felix Scholze) Logo",
    width: 296,
    height: 100,
  },
];

export const funded: Logo[] = [
  {
    name: "DBU",
    logo: DBU,
    url: "https://www.dbu.de/",
    alt: "DBU Logo",
  },
  {
    name: "Stiftung Mercator",
    logo: Mercator,
    url: "https://www.stiftung-mercator.de/",
    alt: "Stiftung Mercator Logo",
  },
  {
    name: "Bundesministerium für Umwelt, Naturschutz und nukleare Sicherheit",
    logo: BMUV,
    url: "https://www.bmu.de/",
    alt: "Bundesministerium für Umwelt, Naturschutz und nukleare Sicherheit Logo",
  },
];

export const organised_by: Logo[] = [
  {
    name: "BUND",
    logo: "/images/logos/traegerinnen/bund.svg",
    url: "https://www.bund.net/",
    alt: "BUND Logo",
    width: 296,
    height: 100,
  },
  {
    name: "Chaos Computer Club",
    logo: "/images/logos/traegerinnen/ccc.svg",
    url: "https://www.ccc.de/",
    alt: "Chaos Computer Club Logo",
    width: 179,
    height: 130,
  },
  {
    name: "Deutscher Naturschutzring",
    logo: "/images/logos/traegerinnen/dnr.svg",
    url: "https://www.dnr.de/",
    alt: "Deutscher Naturschutzring Logo",
    width: 296,
    height: 100,
  },
  {
    name: "Einstein Center Digital Future",
    logo: "/images/logos/traegerinnen/einstein_center.svg",
    url: "https://www.digital-future.berlin/",
    alt: "Einstein Center Digital Future Logo",
    width: 130,
    height: 130,
  },
  {
    name: "Brot für die Welt",
    logo: "/images/logos/traegerinnen/brot-fuer-die-welt.svg",
    url: "https://www.brot-fuer-die-welt.de/",
    alt: "Brot für die Welt Logo",
    width: 231,
    height: 100,
  },
  {
    name: "Free Software Foundation Europe",
    logo: "/images/logos/traegerinnen/fsfe-cropped.svg",
    url: "https://fsfe.org/",
    alt: "Free Software Foundation Europe Logo",
    width: 249,
    height: 130,
  },
  {
    name: "Forum InformatikerInnen für Frieden und gesellschaftliche Verantwortung",
    logo: "/images/logos/traegerinnen/fiff-schwarz.svg",
    url: "https://www.fiff.de/",
    alt: "Forum InformatikerInnen für Frieden und gesellschaftliche Verantwortung Logo",
    width: 262,
    height: 100,
  },
  {
    name: "Institut für ökologische Wirtschaftsforschung",
    logo: "/images/logos/traegerinnen/ioew.svg",
    url: "https://www.ioew.de/",
    alt: "Institut für ökologische Wirtschaftsforschung Logo",
    width: 289,
    height: 100,
  },
  {
    name: "konzeptwerk neue ökonomie",
    logo: "/images/logos/traegerinnen/konzeptwerk.svg",
    url: "https://www.konzeptwerk-neue-oekonomie.org/",
    alt: "konzeptwerk neue ökonomie Logo",
    width: 246,
    height: 130,
  },
  {
    name: "Technische Universität Berlin",
    logo: "/images/logos/traegerinnen/tu-berlin.svg",
    url: "https://www.tu-berlin.de/",
    alt: "Technische Universität Berlin Logo",
    width: 233,
    height: 130,
  },
  {
    name: "Weizenbaum-Institut",
    logo: Weizenbaum,
    url: "https://weizenbaum-institut.de/",
    alt: "Weizenbaum-Institut Logo",
    width: 296,
    height: 105,
  },
  {
    name: "Germanwatch e.V.",
    logo: "/images/logos/traegerinnen/germanwatch.svg",
    url: "https://germanwatch.org/",
    alt: "Germanwatch e.V. Logo",
    width: 296,
    height: 108,
  },
  {
    name: "Open Knowledge Foundation",
    logo: "/images/logos/traegerinnen/okfn.svg",
    url: "https://okfn.de/",
    alt: "Open Knowledge Foundation Logo",
    width: 287,
    height: 130,
  },
];
